### ISSUE TITLE
1000行目までの案です

### ISSUE THREAD

**Issue by MrKono** [notyuk4risan/FTBInteractions_nihongokaYatu#1]
案です。
クエストの✔️のaccept
受け入れる → 了解or理解 しました

L85
FTBQには「JEIの統合機能」が...  → JEIとの連携機能

L153
Hey, Listen！... → 聞いて！or見て

L158
あなたが「トメ」を... → 錬金大全
「特別な」クラブに参... → 悲劇的な

L208
諦めないで

L568
空を歩く者

L612
ダイヤモンドとエメラルドの鉱脈

L736
それは人類にとって小さな一歩であり、大きな飛躍である。

L754&756
持つには冷たすぎる

**Comment by notyuk4risan** [comment]
L153・L568は元ネタ(L153:ゼルダの伝説、L568:スターウォーズ)のニュアンスを考慮してあえて翻訳していません。
その他については参考になりました！L736だけちょっと意訳して反映させます
thx
