### ISSUE TITLE
修正案L1～102

### ISSUE THREAD

**Issue by komet0141** [notyuk4risan/FTBInteractions_nihongokaYatu#3]
L5次に進むには真鍮を用意してください
L8準備をしておいたほうがいいですよ。ほかの人は多分していないので。難易度を上げてくれてありがとうございます。
L14おめでとうございます。あなたのせいで全滅しました。
L22自動化に力を入れてください。
L25オスミウム、イリジウム、プラチナなどの素材を入手するにはここの開拓が必須です。直接カオスガーディアンに挑むも良し、闇の星オーレリアに行って最終段階の技術と魔法をアンロックして自分を強化するのもいいでしょう。
L29GregTechの先進技術のほとんどは生産に大規模なマルチブロックアセンブリーが必要です。
L32鋼鉄はLVへの主要な素材となります。
L34無限への進行
L37こうなる運命です
L38夜明けはまだですか？
L39オーバーワールドへのポータルを作成すると新しく開拓する大地、鉱石、希少素材、魔法、そしてもちろん、、、新しい敵が解放されます。
L44ここではいろいろなものが見つかります。vinteum鉱石、ダンジョン、強力なエイリアンの技術、さらには神話生物のうわさまで、、、
L46この惑星にいると太って見える？
L49少なくともInteractons Expert mode...Kappaが出るまでは。 
L51蒸気がプシューってなってガー
L52少なくともプレートを打ち付ける必要がなくなりました。
L55真鍮を入手するためにこの世界の金属を亜鉛で安定させる必要がありますが、亜鉛は非常にレアです。錬金真鍮を作成するのが最善の策なので、Thaumcraftを始めましょう。
L57進行
L66注入→星光注入
L67井戸→油田
L69適応→活用
L84JEI活用のコツ
L91クエストチェーンの始まり
L94あなたが重要です
L98一束→たくさん
L100情報掲示板

**Comment by notyuk4risan** [comment]
案をいただきまして、ありがとうございます！
わたしの方でよく考えて反映させていただきます！
