### ISSUE TITLE
Error and Suggest

### ISSUE THREAD

**Issue by MrKono** [notyuk4risan/FTBInteractions_nihongokaYatu#4]
// Error
L429 列→行
L1181 =が欠損
L1662 すよ！）。) → すよ！)
L1729 ログ → 原木
L2415 まずプルトニウム244の小さな「山」 → まずプルトニウム244の小さな「粉」

// Suggest
Metallurgy → 冶金or金属加工 (Metallurgy 電圧 タブ)
L684 死の青緑色の水
L849 境界のない箱
L1587 供給連鎖管理
L1582 より大きなバケツ
L1585 ストレージの拡張
L1601 物流の悪夢
L1653 自動農場？ください！
L1683 私がもっと熱くなれればなぁ 
　　(注;超意訳。直訳は「私がこんなにひどく白熱することができれば」)
L1728 原木が不足していないかい？
　　(注;疑問形かどうかは不明)
L1755 もうワンステップ
L1786 驚異的な宇宙の力 (←可能なら太字でもいいかもしれません) ... ちっぽけな卵
L1795 鶏の星
L1813 輝きの星
L1855 食用じゃないよ！
L1957 家庭用化学キット
L1975 バランスの取れた電解
L1979 進歩のナゲット
L2095 攻撃的な豚の声
L2161 スライム島はありません
L2175 空に制限はない！
L2389 なにこれ？反物質！

小文字と大文字を統一(バケツ[bとB]や電力[euとEU])したほうが良いかもしれません。

**Comment by notyuk4risan** [comment]
thx comment
