### ISSUE TITLE
error/suggestL103-L1000

### ISSUE THREAD

**Issue by komet0141** [notyuk4risan/FTBInteractions_nihongokaYatu#5]
error
L161修繕ついている→修繕がついている
L187貧弱な→可哀そうなことに
L197このようにして作られた板は、8枚以下にします。→この方法で作る木材は8個もあれば足りるでしょう。
L226取り出しし→取り出し
L288ベースをよりきれいにするために→拠点を美しくするために
L320初期の使用感も十分ですが→初期のたくさんの用途があり、
L565は手を離すかして→オフハンドに持って
L709オレゴン→鉱石生成
L736それは人類にとって小さな一歩であり、大きな一歩でもある→これは人間による小さな一歩だが、人類にとっては大きな一歩である。
L929石を砕いた後は粉砕するか、ハンマーで鍛えるか、ハンマーで形を整えるかして、→鉱石を砕いた後は粉砕、打砕、ハンマーとクラフトするなどして、
suggest
L105BetterThanBoneMeal(TM)→株式会社骨粉の上位互換
L107ライブラリーカード→図書カード
L107チゼル→変換
L164そして→それと
L178Better Building Wand→より良い建築ツール
L189ここまでスクロールしてきた→このクエストを見に来た
L200IF ONLY... (ヒント：賢者の石の英名と韻を踏んでいます)→もしあれば... (ヒント：けん者の岸と韻を踏んでいます)
L229The Wood Barber→木の美容師
L251Hot or Not?→熱いか否か
L254Filo Stone→賢石
L286倒す→完走する
L300Rain-B-Gone→明日天気になーれ
L374Shake it off→振り落とす
L510ジャーナル→記事
L530Not Quite Diamonds→ダイヤモンドではない
L533ツリーファーム→植林場
L698Space Raced!→宇宙競争！
L762Basement Chemistry Kit→拠点の化学キット
L952Higher tier rituals, Yes please!→もっといい祭壇が欲しい！

**Comment by notyuk4risan** [comment]
Thx
